### ISSUE TITLE
On page load/reload images aren't loading in the viewport until the first scroll event

### ISSUE THREAD

**Issue by seandogg** [estrattonbailey/lazim#5]
This is probably something to do with the way I've setup my slater theme, but when the user makes a reload, say halfway down the page... lazim isn't loading any images until the first scroll event on the window. Same is true for the top of page first load... Is there a way to load any images that are already in the viewport before scrolling? Or an option that sets it just below the viewport? 

Thanks again for sharing these contributions, learning quite a bit from your setups, and it's much appreciated!

**Comment by slavafyi** [comment]
I faced the same problem. You didn't find a solution? @seandogg 

However, if we change the size of the viewport (flip the device or change the size of the browser window) then the images are loaded. @estrattonbailey 

**UPD:**
I solved it😅 The problem was that I had a height of 100% set for the html tag, and when I removed this rule, everything worked perfectly.
